CREATE TABLE [dbo].[PARTICIPANTES]
(
	[pessoa] INT NOT NULL , 
    [projeto] INT NOT NULL, 
    [tipo] INT NOT NULL, 
    PRIMARY KEY ([pessoa], [projeto]), 
    CONSTRAINT [FK_PARTICIPANTES_PESSOA] FOREIGN KEY ([pessoa]) REFERENCES [PESSOAS]([id]), 
    CONSTRAINT [FK_PARTICIPANTES_TIPO] FOREIGN KEY ([tipo]) REFERENCES [TIPO_PARTICIPANTE]([id]) 
)
