CREATE TABLE [dbo].[PESSOAS]
(
	[id] INT NOT NULL PRIMARY KEY, 
    [nome] VARCHAR(50) NOT NULL, 
    [gestor] INT NULL, 
    CONSTRAINT [FK_PESSOAS_GESTOR] FOREIGN KEY (gestor) REFERENCES PESSOAS([id])
)
