'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace CPWebApp

    Partial Public Class CPDatabaseEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=CPDatabaseEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property PARTICIPANTES() As DbSet(Of PARTICIPANTES)
        Public Overridable Property PESSOAS() As DbSet(Of PESSOAS)
        Public Overridable Property PROJETOS() As DbSet(Of PROJETOS)
        Public Overridable Property RECURSOS() As DbSet(Of RECURSOS)
        Public Overridable Property SISTEMAS() As DbSet(Of SISTEMAS)
        Public Overridable Property SOLICITACOES() As DbSet(Of SOLICITACOES)
        Public Overridable Property TIPO_PARTICIPANTE() As DbSet(Of TIPO_PARTICIPANTE)
        Public Overridable Property TIPO_RECURSO() As DbSet(Of TIPO_RECURSO)
    
    End Class

End Namespace
