'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CPWebApp

    Partial Public Class PARTICIPANTES
        Public Property pessoa As Integer
        Public Property projeto As Integer
        Public Property tipo As String
    
        Public Overridable Property PESSOAS As PESSOAS
    
    End Class

End Namespace
