//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PARTICIPANTES
    {
        [Display(Name = "Pessoa")]
        public int pessoa { get; set; }

        [Display(Name = "Projeto")]
        public int projeto { get; set; }

        [Display(Name = "Tipo de participante")]
        public int tipo { get; set; }
    
        public virtual PESSOAS PESSOAS { get; set; }
    }
}
