'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CPWebApp

    Partial Public Class RECURSOS
        Public Property id As Integer
        Public Property pessoa As Integer
        Public Property sistema As Integer
        Public Property tipo As Integer
    
        Public Overridable Property PESSOAS As PESSOAS
        Public Overridable Property SISTEMAS As SISTEMAS
        Public Overridable Property TIPO_RECURSO As TIPO_RECURSO
    
    End Class

End Namespace
