'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CPWebApp

    Partial Public Class SISTEMAS
        Public Property id As Integer
        Public Property nome As String
    
        Public Overridable Property PROJETOS As ICollection(Of PROJETOS) = New HashSet(Of PROJETOS)
        Public Overridable Property RECURSOS As ICollection(Of RECURSOS) = New HashSet(Of RECURSOS)
        Public Overridable Property SOLICITACOES As ICollection(Of SOLICITACOES) = New HashSet(Of SOLICITACOES)
    
    End Class

End Namespace
