'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CPWebApp

    Partial Public Class TIPO_PARTICIPANTE
        Public Property id As Integer
        Public Property titulo As String
        Public Property insere_documentos As Nullable(Of Boolean)
    
    End Class

End Namespace
