'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CPWebApp

    Partial Public Class TIPO_RECURSO
        Public Property id As Integer
        Public Property titulo As String
        Public Property cria_solicitacao As Nullable(Of Boolean)
        Public Property cria_projeto As Nullable(Of Boolean)
        Public Property aprova_solicitacao As Nullable(Of Boolean)
        Public Property aprova_projeto As Nullable(Of Boolean)
    
        Public Overridable Property RECURSOS As ICollection(Of RECURSOS) = New HashSet(Of RECURSOS)
    
    End Class

End Namespace
