//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [DisplayName("Tipo de Participante")]
    public partial class TIPO_PARTICIPANTE
    {
        [Display(Name = "ID")]
        public int id { get; set; }

        [Display(Name = "Título")]
        public string titulo { get; set; }
        public Nullable<bool> insere_documentos { get; set; }
    }
}
