//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIPO_RECURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_RECURSO()
        {
            this.RECURSOS = new HashSet<RECURSOS>();
        }

        [Display(Name = "ID")]
        public int id { get; set; }

        [Display(Name = "Título")]
        public string titulo { get; set; }

        [Display(Name = "Cria solicitação?")]
        public Nullable<bool> cria_solicitacao { get; set; }

        [Display(Name = "Cria projeto?")]
        public Nullable<bool> cria_projeto { get; set; }

        [Display(Name = "Aprova solicitação?")]
        public Nullable<bool> aprova_solicitacao { get; set; }

        [Display(Name = "Aprova projeto?")]
        public Nullable<bool> aprova_projeto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSOS> RECURSOS { get; set; }
    }
}
